version: "3.9"
services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: thebarapp_db
      MYSQL_USER: root
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql

  app:
    build: ./backend
    container_name: thebarapp
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env # ton .env existant
    depends_on:
      - db
